#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
# general space settings
yabai -m config layout                       bsp

# Borders no longer working since v6
# yabai -m config window_border on
# yabai -m config window_border_blur off
# yabai -m config window_border_width          4
# yabai -m config active_window_border_color 0xFF88CC99
# yabai -m config normal_window_border_color 0x002E3440

yabai -m config insert_feedback_color 0xFFA3BE8C


yabai -m config menubar_opacity 1

#Options that need SIP desabled
yabai -m config window_animation_duration    0.0
# yabai -m config window_animation_frame_rate  120 # deprecated since 6.0.10

#
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        0.0
yabai -m config normal_window_opacity        0.0

# Padding 
yabai -m config top_padding                  12 
yabai -m config bottom_padding               12 
yabai -m config left_padding                 12 
yabai -m config right_padding                12 

yabai -m config window_gap                   12

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
# yabai -m config window_placement             second_child
# floating windows are always on top (default: off)
yabai -m config window_topmost               off
# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow                off

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m rule --add app=".*" layer=normal # to solve a but when all floats where sticky

yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^AppCleaner$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Bazecor$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Installer$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^League of Legends$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Mail$" manage=off
yabai -m rule --add app="^Microsoft Outlook$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^NordPass$" manage=off
yabai -m rule --add app="^NordVPN$" manage=off
yabai -m rule --add app="^OpenVPN Connect$" manage=off
yabai -m rule --add app="^Paralells Desktop$" manage=off
yabai -m rule --add app="^Pika$" manage=off
yabai -m rule --add app="^Power Bi Desktop$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Riot Client$" manage=off
yabai -m rule --add app="^Shortcuts$" manage=off
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Terminal$" manage=off
yabai -m rule --add app="^TextEdit$" manage=off
yabai -m rule --add app="^Upwork$" manage=off
yabai -m rule --add app="^VNC Viewer$" manage=off
yabai -m rule --add app="^WhatsApp$" manage=off
yabai -m rule --add app="^Windows 11$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Notes$" manage=off 



echo "yabai configuration aded.."
# paste any hex after 0xff to change the color of the borders
borders active_color=0xff7962D6 inactive_color=0xff494d64 width=5.0 &
