set -g default-terminal "screen-256color"
# set-option -sa terminal-overrides ",xterm*:Tc"

# Remapped prefix key
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Pane splitting 
unbind %
bind ] split-window -h -c "#{pane_current_path}"
unbind '"'
bind [ split-window -v -c "#{pane_current_path}"

# Source files
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Pane resizing

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on
unbind -T copy-mode-vi MouseDragEnd1Pane

# Scroll speed
bind-key -T copy-mode-vi WheelUpPane send -N1 -X scroll-up
bind-key -T copy-mode-vi WheelDownPane send -N1 -X scroll-down

# Active window color
set-window-option -g window-status-current-style bg=red

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Start window at index 1, not 0 
set -g base-index 1
setw -g pane-base-index 1 
# set-window-option -g pane-base-index 1 
# set-option -g renumber-windows on 


# List of plugins
# Must have
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'


# styles
set -g @plugin 'dracula/tmux'

# catppuccin flavor
# set -g @catppuccin_flavor 'latte'
# set -g @plugin 'catppuccin/tmux'
# set -g @plugin 'dreamsofcode-io/catppuccin-tmux'

# set -g @plugin 'jimeh/tmux-themepack'
# set -g @themepack 'powerline/default/cyan'

set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # or 'light'

# Perist files
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

